
type ProjectNode = {
  id: string;
  position: [number, number, number];
  color?: string;
};

type ProjectEdge = {
  from: string;
  to: string;
  color?: string;
};

const green = "#00C851";
const orange = "#F5721A";
const red = "#CC2222";
const purple = "#9370DB";

// 노드 및 엣지 정의
export const ssssksssBlogProjectNodes: ProjectNode[] = [
  {id: "메인", position: [0, 0, 0], color: green},
  {id: "블로그", position: [1, 0, 0], color: red},
  {id: "블로그 목록 조회", position: [3, 0, 0], color: red},
  {id: "블로그 생성", position: [7, 3, 0], color: red},
  {id: "블로그 조회", position: [5, 0, 0], color: red},
  {id: "블로그 수정", position: [7, -1, 0], color: red},
  {id: "블로그 기초 글 목록", position: [9, 3, 0], color: red},
  {id: "블로그 기초 글 찾기", position: [12, 4, 0], color: red},
  {id: "블로그 기초 글 삭제", position: [15, 4, 0], color: red},
  {id: "블로그 기초 글 수정", position: [12, 3, 0], color: red},
  {id: "블로그 기초 글 생성", position: [12, 2, 0], color: red},
  {id: "블로그 구조 글 목록", position: [9, -1, 0], color: red},
  {id: "블로그 구조 글 찾기", position: [12, 0, 0], color: red},
  {id: "블로그 구조 글 삭제", position: [15, 0, 0], color: red},
  {id: "블로그 구조 글 수정", position: [12, -1, 0], color: red},
  {id: "블로그 구조 글 생성", position: [12, -2, 0], color: red},
  {id: "블로그 결과 글 목록", position: [9, -4, 0], color: red},
  {id: "블로그 결과 글 생성", position: [12, -4, 0], color: red},
  {id: "블로그 결과 글 삭제", position: [12, -5, 0], color: red},
  {id: "블로그 결과 글 수정", position: [12, -6, 0], color: red},
  {id: "블로그 삭제", position: [7, -3, 0], color: red},
  {id: "게시판", position: [-1, 0, 0], color: red},
  {id: "게시판 목록 조회", position: [-3, 0, 0], color: red},
  {id: "게시판 조회", position: [-5, 0, 0], color: red},
  {id: "게시판 수정", position: [-7, 1, 0], color: red},
  {id: "게시판 삭제", position: [-7, 0, 0], color: red},
  {id: "게시판 댓글", position: [-7, -1, 0], color: red},
  {id: "일정", position: [-1, -8, 0], color: red},
  {id: "일정 달력", position: [-3, -6, 0], color: red},
  {id: "일정 카테고리 목록", position: [-5, -4, 0], color: red},
  {id: "일정 카테고리 생성", position: [-8, -3, 0], color: red},
  {id: "일정 카테고리 수정", position: [-8, -4, 0], color: red},
  {id: "일정 카테고리 삭제", position: [-8, -5, 0], color: red},
  {id: "일정 목록 조회", position: [-5, -7, 0], color: red},
  {id: "일정 생성", position: [-7, -6, 0], color: red},
  {id: "일정 조회", position: [-7, -7, 0], color: red},
  {id: "일정 수정", position: [-9, -7, 0], color: red},
  {id: "일정 삭제", position: [-9, -8, 0], color: red},
  {id: "일정 홈", position: [-3, -8, 0], color: red},
  {id: "메모", position: [-3, -10, 0], color: red},
  {id: "메모 생성", position: [-5, -10, 0], color: red},
  {id: "메모 목록 조회", position: [-5, -12, 0], color: red},
  {id: "메모 수정", position: [-7, -11, 0], color: red},
  {id: "메모 삭제", position: [-7, -13, 0], color: red},
  {id: "헤더", position: [1, 8, 0], color: green},
  {id: "다크모드", position: [3, 7, 0], color: red},
  {id: "폴링효과", position: [3, 6, 0], color: red},
  {id: "인증", position: [3, 9, 0], color: purple},
  {id: "사이드바", position: [3, 12, 0], color: green},
  {id: "음악 플레이어", position: [5, 12, 0], color: orange},
  {id: "플레이리스트 생성", position: [7, 11, 0], color: green},
  {id: "플레이리스트 목록 조회", position: [7, 13, 0], color: green},
  {id: "플레이리스트 삭제", position: [7, 15, 0], color: green},
  {id: "유튜브 URL 삭제", position: [10, 11, 0], color: red},
  {id: "유튜브 URL 등록", position: [10, 13, 0], color: green},
  {id: "유튜브 URL 실행", position: [10, 15, 0], color: orange},
  {id: "즐겨찾기", position: [-1, 3, 0], color: red},
  {id: "즐겨찾기 목록 조회", position: [-3, 5, 0], color: red},
  {id: "즐겨찾기 카테고리 등록", position: [-5, 8, 0], color: red},
  {id: "즐겨찾기 카테고리 삭제", position: [-5, 6, 0], color: red},
  {id: "즐겨찾기 등록", position: [-5, 4, 0], color: red},
  {id: "즐겨찾기 삭제", position: [-5, 2, 0], color: red},
];


export const ssssksssBlogProjectEdges: ProjectEdge[] = [
  {from: "메인", to: "블로그"},
  {from: "블로그", to: "블로그 목록 조회"},
  {from: "블로그 목록 조회", to: "블로그 생성"},
  {from: "블로그 생성", to: "블로그 기초 글 목록"},
  {from: "블로그 생성", to: "블로그 구조 글 목록"},
  {from: "블로그 생성", to: "블로그 결과 글 목록"},
  {from: "블로그 목록 조회", to: "블로그 조회"},
  {from: "블로그 조회", to: "블로그 기초 글 목록", color: "green"},
  {from: "블로그 조회", to: "블로그 구조 글 목록", color: "green"},
  {from: "블로그 조회", to: "블로그 결과 글 목록", color: "green"},
  {from: "블로그 조회", to: "블로그 수정"},
  {from: "블로그 조회", to: "블로그 삭제"},
  {from: "블로그 수정", to: "블로그 기초 글 목록"},
  {from: "블로그 기초 글 목록", to: "블로그 기초 글 찾기"},
  {from: "블로그 기초 글 찾기", to: "블로그 기초 글 삭제"},
  {from: "블로그 기초 글 목록", to: "블로그 기초 글 수정"},
  {from: "블로그 기초 글 목록", to: "블로그 기초 글 생성"},
  {from: "블로그 수정", to: "블로그 구조 글 목록"},
  {from: "블로그 구조 글 목록", to: "블로그 구조 글 찾기"},
  {from: "블로그 구조 글 찾기", to: "블로그 구조 글 삭제"},
  {from: "블로그 구조 글 목록", to: "블로그 구조 글 수정"},
  {from: "블로그 구조 글 목록", to: "블로그 구조 글 생성"},
  {from: "블로그 수정", to: "블로그 결과 글 목록"},
  {from: "블로그 결과 글 목록", to: "블로그 결과 글 생성"},
  {from: "블로그 결과 글 목록", to: "블로그 결과 글 수정"},
  {from: "블로그 결과 글 목록", to: "블로그 결과 글 삭제"},
  {from: "메인", to: "게시판"},
  {from: "게시판", to: "게시판 목록 조회"},
  {from: "게시판 목록 조회", to: "게시판 조회"},
  {from: "게시판 조회", to: "게시판 수정"},
  {from: "게시판 조회", to: "게시판 삭제"},
  {from: "게시판 조회", to: "게시판 댓글"},
  {from: "메인", to: "일정"},
  {from: "일정", to: "일정 홈"},
  {from: "일정", to: "일정 달력"},
  {from: "일정 달력", to: "일정 카테고리 목록"},
  {from: "일정 카테고리 목록", to: "일정 카테고리 생성"},
  {from: "일정 카테고리 목록", to: "일정 카테고리 수정"},
  {from: "일정 카테고리 목록", to: "일정 카테고리 삭제"},
  {from: "일정 달력", to: "일정 생성"},
  {from: "일정 달력", to: "일정 목록 조회"},
  {from: "일정 목록 조회", to: "일정 조회"},
  {from: "일정 목록 조회", to: "일정 생성"},
  {from: "일정 조회", to: "일정 수정"},
  {from: "일정 조회", to: "일정 삭제"},
  {from: "일정", to: "메모"},
  {from: "메모", to: "메모 생성"},
  {from: "메모", to: "메모 목록 조회"},
  {from: "메모 목록 조회", to: "메모 수정"},
  {from: "메모 목록 조회", to: "메모 삭제"},
  {from: "메인", to: "헤더"},
  {from: "헤더", to: "인증"},
  {from: "헤더", to: "다크모드"},
  {from: "헤더", to: "폴링효과"},
  {from: "헤더", to: "사이드바"},
  {from: "사이드바", to: "음악 플레이어"},
  {from: "음악 플레이어", to: "플레이리스트 생성"},
  {from: "음악 플레이어", to: "플레이리스트 목록 조회"},
  {from: "플레이리스트 목록 조회", to: "플레이리스트 삭제"},
  {from: "플레이리스트 목록 조회", to: "유튜브 URL 삭제"},
  {from: "플레이리스트 목록 조회", to: "유튜브 URL 등록"},
  {from: "플레이리스트 목록 조회", to: "유튜브 URL 실행"},
  {from: "메인", to: "즐겨찾기"},
  {from: "즐겨찾기", to: "즐겨찾기 목록 조회"},
  {from: "즐겨찾기 목록 조회", to: "즐겨찾기 카테고리 등록"},
  {from: "즐겨찾기 목록 조회", to: "즐겨찾기 카테고리 삭제"},
  {from: "즐겨찾기 목록 조회", to: "즐겨찾기 등록"},
  {from: "즐겨찾기 목록 조회", to: "즐겨찾기 삭제"},
];